### ISSUE TITLE
点击单元格，为什么会触发分页的current-change事件？？？

### ISSUE THREAD

**Issue by uino-wuixn** [pure-admin/pure-admin-table#10]
![image](https://user-images.githubusercontent.com/73518894/222038155-6e0e1479-bd74-4c25-af82-b9c6cef5069c.png)

**Comment by uino-wuixn** [comment]
是因为表格和分页都有current-change导致命名冲突了吗

**Comment by uino-wuixn** [comment]
看源码才知道page-current-change

**Comment by uino-wuixn** [comment]
哥们，你这个没有一个文档吗

**Comment by xiaoxian521** [comment]
[el-table](https://element-plus.org/zh-CN/component/table.html)的`api`，它都会保持一致，其他的参考https://github.com/pure-admin/vue-pure-admin/tree/main/src/views/pure-table，感觉没必要给文档
