### ISSUE TITLE
【BUG】pure-table的current-change事件和分页的current-change重合了，导致触发table的current-change事件时，分页的current-change事件也会被触发

### ISSUE THREAD

**Issue by dongjinhai** [pure-admin/pure-admin-table#11]
![image](https://user-images.githubusercontent.com/18241524/222669154-7150bb6d-1c93-4194-9f2c-9d9bf6590bfb.png)
![image](https://user-images.githubusercontent.com/18241524/222669227-a7cf1cf9-e62f-415d-8ff1-e578cd44d33f.png)
![image](https://user-images.githubusercontent.com/18241524/222669343-00024035-f806-44bf-bc0a-44ea016365fd.png)

**Comment by xiaoxian521** [comment]
[分页事件名变更 size-change 变更为 page-size-change、current-change 变更为 page-current-change](https://github.com/pure-admin/pure-admin-table/releases/tag/v2.0.0)
