### ISSUE TITLE
多选情况下，分页会导致前面选择的数据丢失

### ISSUE THREAD

**Issue by lvpv** [pure-admin/pure-admin-table#14]
表格开启多选的情况下，切换页码，表格会刷新，前端选择的数据会丢失

**Comment by xiaoxian521** [comment]
这个需要自行处理哈 并不在该组件的考虑场景

**Comment by ZexinW** [comment]
el-table自带这种功能.
请详细阅读,官方文档reserve-selection属性.

对于 pure-table来说需要这样设置,并且配置row-key属性,即可生效.
![image](https://github.com/pure-admin/pure-admin-table/assets/110024406/72dc4944-c21c-4d69-914a-a13b5ec53a97)
