### ISSUE TITLE
似乎没有有虚拟列表的设置

### ISSUE THREAD

**Issue by GoodNight-momoda** [pure-admin/pure-admin-table#17]
表格都是全量加载，有虚拟加载列表就更好了！表格数据太多会导致卡顿

**Comment by xiaoxian521** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/44761321/234745653-d686d4ea-76a3-4b59-aa8b-e7a8a040b929.png">

**Comment by GoodNight-momoda** [comment]
不好意思没看到，谢谢解答！
