### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by itangqiao** [pure-admin/pure-admin-table#19]
runtime-core.esm-bundler.js:7482  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'exposed')

**Comment by xiaoxian521** [comment]
无法复现 参考 https://github.com/pure-admin/pure-admin-table/tree/main/playgrounds
需要确定并解决问题请提供完整的复现步骤或者demo示例 简单的issues一律过滤
