### ISSUE TITLE
希望增加客户端分页功能。

### ISSUE THREAD

**Issue by wuhao-max** [pure-admin/pure-admin-table#21]
希望增加本地分页功能，例如接口一次返回1000条数据，此时需要本地分页，希望作者可以封装一下，传个参数就可以开启本地分页。
另外希望作业可以把单选模式改成前面是<el-radio>单选框这种的形式，类似于antdesign，更符合单选行的样式。
既然作者二次封装了el-table，那么希望可以比el-table更好，不止是简化了columns的写法而已，望采纳！
最后，还是感谢大佬的付出，开源不易，我先点个star为敬！

**Comment by xiaoxian521** [comment]
认真看下 https://github.com/pure-admin/pure-admin-table/blob/main/packages/components/table/index.tsx#L271

**Comment by wuhao-max** [comment]
> 认真看下 https://github.com/pure-admin/pure-admin-table/blob/main/packages/components/table/index.tsx#L271

好的，谢谢。
还有个问题想问下，单选模式可以改成前面是单选框这种的形式，类似于antdesign，更符合单选行的样式。目前有这种属性能控制吗？

**Comment by xiaoxian521** [comment]
https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/index?username=sso&roles=admin&accessToken=eyJhbGciOiJIUzUxMiJ9.admin

**Comment by wuhao-max** [comment]
大哥，你这回复也太敷衍了吧。。。看都没看我的问题 - -，
我就是看了例子，没有才来git上提的。我的意思是类似于这种单选行的:
![image](https://github.com/pure-admin/pure-admin-table/assets/39900695/3b957f05-8a60-4e62-877e-3d9f0a0f3165)

**Comment by xiaoxian521** [comment]
好好看readme
能回复你这些问题就不错了 
文档有的一概不回复
el-table有这个就有

**Comment by wuhao-max** [comment]
我知道啊，我的意思是你能不能在el-table的基础上增加一些功能？如果不能提这个的话，那就当我没说，我直接去看el-table的文档了

**Comment by xiaoxian521** [comment]
对啊
readme写的清清楚楚
