### ISSUE TITLE
列设置中列默认状态不正确

### ISSUE THREAD

**Issue by hogking** [pure-admin/pure-admin-table#23]
你好，
我的某列配置如下：
{
      ...
      minWidth: 130,
      fixed: true,
      hide: true
}。
表格是隐藏展示该列了，但在“列设置”中该列默认状态还是已被选中状态。

**Comment by xiaoxian521** [comment]
`列设置`非`pure-admin-table`的配置，请去 https://github.com/pure-admin/vue-pure-admin 提 `issues`
