### ISSUE TITLE
没有BUG

### ISSUE THREAD

**Issue by zhang-wei-jian** [pure-admin/pure-admin-table#26]
如果如果数组是带有chilren的子数组是正常的，但是如果chilren还有chilren嵌套了这个chilren中的chilren位置就会错
<img width="1853" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/75430336/8eae4e2a-70c7-45c9-902b-a5f46b291e79">
费需要你的帮助

**Comment by zhang-wei-jian** [comment]
可以看到这个
<img width="382" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/75430336/9c164349-7798-4a9f-af5d-154f84dd51b0">
位置是不对的，因为他是嵌套的chilren，我也测试了element的没有bug还有虚拟的element的虚拟table也没有这种问题

**Comment by xiaoxian521** [comment]
提供具体复现仓库

**Comment by zhang-wei-jian** [comment]
非常抱歉，是我粗心，我找到了问题所在是自己设的宽度问题导致的，非常感谢您
