### ISSUE TITLE
关于表格使用pagination分页的问题

### ISSUE THREAD

**Issue by wbsllm** [pure-admin/pure-admin-table#27]
我在自己的项目中, 用了pure-table, 因为某些原因必须是用yarn来安装依赖包.
但在pure-table使用分页时,发现是英文的.
排除没有设置elementPlus为中文显示,因为在app.vue使用了el-config-provider :locale="zhCn"的方式来设置全局中文.
后将依赖包全部删除,使用pnpm安装依赖包, 在pure-table使用分页时,发现是中文的
再删除全部依赖包,使用yarn安装依赖包,在pure-table使用分页时,发现是英文的,问题复现..

补充说明: 使用yarn下载的依赖包时,使用el-config-provider组件单独包裹pure-table也无效.

**Comment by wbsllm** [comment]
补充说明: 使用yarn下载的依赖包时,使用el-config-provider组件单独包裹pure-table也无效. 
<el-config-provider :locale="zhCn">
    <pure-table :pagination="pagination"></pure-table>
  </el-config-provider>

**Comment by xiaoxian521** [comment]
[duplicate](https://github.com/pure-admin/pure-admin-table/issues/3)

**Comment by xiaoxian521** [comment]
国际化配置与本项目 完美没有任何关系 本项目不管国际化 也没有任何国际化的代码 参考 https://element-plus.org/zh-CN/guide/i18n.html#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE
