### ISSUE TITLE
pure-table 中 `LoadingConfig` 配置 `background` 不生效问题

### ISSUE THREAD

**Issue by Liuzebiao** [pure-admin/pure-admin-table#28]
**描述问题：**
代码见图片：https://test-1318510234.cos.ap-beijing.myqcloud.com/loading%E4%B8%ADbackground%E5%B1%9E%E6%80%A7%E4%B8%8D%E7%94%9F%E6%95%88%E9%97%AE%E9%A2%98%E4%BB%A3%E7%A0%81%E4%BD%8D%E7%BD%AE.png

此处的background好像不生效。背景我只调试出来2种情况就是rgba(0,0,0,0.45) 和 rgba(255,255,255,0.45)

**如何复现该问题 (How to reproduce the problem)**
官方demo即可测试出来

**Comment by xiaoxian521** [comment]
修复：https://github.com/pure-admin/pure-admin-table/releases/tag/v2.3.3

如果你要自定义背景色并且需要适配暗黑模式，参考下图红框代码即可
<img width="1552" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/44761321/67f2f5a1-9b6f-447c-91b0-f302989e0c63">
