### ISSUE TITLE
feat: 希望增加CRUD最佳实践

### ISSUE THREAD

**Issue by lihuacai168** [pure-admin/pure-admin-table#30]
在后台管理系统中，一般都是新增，编辑，搜索，查询单个记录的详情这些功能
我自己的实现，新增和编辑共用一个Dialog
最上方的搜索栏，单独抽出来一个公共组件，包含查询和重置按钮，提供一个插槽，让父组件index.vue来写具体的查询字段
但感觉自己的希望不够优雅
希望可以给出一个最佳实践，最好是搭配mock api
比如下面的截图
<img width="1359" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/11568297/773d9d29-db70-4257-9f6f-6c625f6ca61b">
<img width="904" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/11568297/c276af83-84eb-43cb-96d1-4ccbd53d9f84">
<img width="907" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/11568297/93ee58e7-7f8f-4843-8257-9f62447084c8">

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/tree/main/src/views/system
