### ISSUE TITLE
文档有问题

### ISSUE THREAD

**Issue by huajiujiang** [pure-admin/pure-admin-table#35]
<img width="421" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/105536345/7bd95906-16f7-41b1-af41-9d8c2ccb27db">
github没找到views这个文件夹在哪儿

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/blob/main/src/views/pure-table/base/base.vue
