### ISSUE TITLE
current-page事件问题

### ISSUE THREAD

**Issue by TheTimeMachine** [pure-admin/pure-admin-table#37]
作者大大，pr关得有点快，你试试传current-page再切换分页，是有问题的，table的current-page也输出了pagination的分页

**Comment by xiaoxian521** [comment]
我的意思是
`current-change`触发就看做table的事件
`page-current-change`触发就看做pagination的事件 
这么讲 很明显了吧

**Comment by xiaoxian521** [comment]
如果还未理解 请带上详细代码截图 再提issues

**Comment by TheTimeMachine** [comment]
哎  我知道current-change当做table的事件了  可我现在用current-change事件去切换分页时输出的是pagination的值啊
![企业微信截图_16958051516958](https://github.com/pure-admin/pure-admin-table/assets/47710299/2c13d0db-ff1e-4055-b234-4e2ef9eedf67)

**Comment by xiaoxian521** [comment]
分页用`page-current-change`啊 醉了

**Comment by TheTimeMachine** [comment]
page-current-change我不是用了嘛  还打印了  就在下面  上面的输出就是current-change切换分页时输出的  反正table的current-change我用不来  只能用row-click了  谢谢了
