### ISSUE TITLE
是否可以考虑参考element ui 官方文档，提供类似的页面，更方便的查看组件的所有属性、方法、事件、插槽？

### ISSUE THREAD

**Issue by sunny1028** [pure-admin/pure-admin-table#38]
是否考虑整理文档 ，提供类似element ui 官方文档的页面，更方便的查看组件的所有属性、方法、事件、插槽， 而不用每次去github看源码。

_Originally posted by @sunny1028 in https://github.com/pure-admin/pure-admin-table/issues/31#issuecomment-1722773082_

**Comment by xiaoxian521** [comment]
参考示例 目前没时间写文档 也不考虑
