### ISSUE TITLE
希望自定义高度的offsetBottom支持百分比

### ISSUE THREAD

**Issue by zxzf1234** [pure-admin/pure-admin-table#39]
有时候页面布局是上面一个table占60%高度，下面有个tab之类的空间占40%高度，这个时候使用自定义高度的offsetBottom 不同分辨率情况下的布局会有问题

**Comment by xiaoxian521** [comment]
这个给不了百分比 https://github.com/pure-admin/pure-admin-table/blob/main/packages/components/table/index.tsx#L202
自己可以动态处理offsetBottom

**Comment by zxzf1234** [comment]
window.innerHeight -
        tableWrapper.getBoundingClientRect().top -
        -  window.innerHeight*40%
这样可以吗 不用特别准确 

相对于自定义高度 我更想要的是table自动填满父dom元素  大佬这个可以实现吗

**Comment by xiaoxian521** [comment]
业务层动态处理 `offsetBottom` 应该是最优解

**Comment by zxzf1234** [comment]
好的 感谢大佬解答
