### ISSUE TITLE
配置filters属性,它不是响应式的

### ISSUE THREAD

**Issue by wbsllm** [pure-admin/pure-admin-table#40]
配置了filters属性,假设值是filtersList一个响应式的ref数组,结果filtersList变化了, filters数组无变化;
如果使用普通的 <el-table-column label="文本"  :filters="filterBarcodeList" />标签方式,则没有这个问题

**Comment by wbsllm** [comment]
![image](https://github.com/pure-admin/pure-admin-table/assets/72794088/54ebdc3b-8741-46e8-9aec-5f91dc4f39a0)

**Comment by xiaoxian521** [comment]
先用el-table原版复现

**Comment by xiaoxian521** [comment]
举出详细例子 这里跟框架貌似没一点关系

**Comment by wbsllm** [comment]
`<script setup lang="ts">
import { ref } from "vue";
defineOptions({
  name: "Welcome"
});

const filterBarcodeList = ref<any[]>([]);
const tableData = ref<any[]>([]);
tableData.value = Array.from({ length: 10 }).map((_, idx) => ({
  barcode: `barcode ${idx + 1}`,
  title: `title ${idx + 1}`
}));
// 下面代码的数组可以加载
// filterBarcodeList.value = Array.from({ length: 10 }).map((_, idx) => ({
//   text: `barcode ${idx + 1}`,
//   value: `value ${idx + 1}`
// }));

//以下代码的数组异步不加载
setTimeout(() => {
  filterBarcodeList.value = Array.from({ length: 10 }).map((_, idx) => ({
    text: `barcode ${idx + 1}`,
    value: `value ${idx + 1}`
  }));
}, 1000);

const columns: TableColumnList = [
  {
    type: "expand",
    slot: "expand",
    width: 60
  },
  {
    label: "条码",
    prop: "barcode",
    align: "center",
    // filterMethod: filterHandler,
    filters: filterBarcodeList.value
    // columnKey: "filterBarcode",
  },
  {
    label: "名称",
    prop: "title",
    align: "center"
  }
];
</script>

<template>
  <pure-table ref="tableRef" border :columns="columns" :data="tableData">
  </pure-table>
</template>
`

**Comment by wbsllm** [comment]
应该说是 异步产生的数据, filters数组就没反应了

**Comment by xiaoxian521** [comment]
动态改变 columns
