### ISSUE TITLE
getSelectionRows 这个怎么使用

### ISSUE THREAD

**Issue by figo361** [pure-admin/pure-admin-table#46]
multebleref.value.getSelectionRows()这样写提示
![image](https://github.com/pure-admin/pure-admin-table/assets/6834921/9b5cbd9c-21b9-4b17-902d-eccc599c0961)

**Comment by xiaoxian521** [comment]
看demo哈 目前不解决非bug问题

**Comment by figo361** [comment]
谢谢大佬，没认真看
