### ISSUE TITLE
我希望能动态控制列的显隐

### ISSUE THREAD

**Issue by ScalaFirst** [pure-admin/pure-admin-table#47]
我使用 TableColumns 的 hide 参数，传入 一个 function，返回一个动态的boolean值，初始值为false。

{
hide: () => show.value
}

但是当我修改 show.value = true 后，隐藏的列没有恢复显示。请问有办法实现这个功能吗？

**Comment by xiaoxian521** [comment]
demo都是例子啊 自行参考
