### ISSUE TITLE
为啥分页是英文的,能在那里设置

### ISSUE THREAD

**Issue by yh710321093** [pure-admin/pure-admin-table#53]
![微信图片_20231201172147](https://github.com/pure-admin/pure-admin-table/assets/63218962/950d13bb-7221-4948-8bb1-a42bc04dca2e)
就正常的装包,页面内引入使用,出来后分页是英文的

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/pure-admin-table/issues/27
