### ISSUE TITLE
分页的样式可以配置成显示表格右下角吗？紧挨着那。现在是固定下最底部。有这种属性可以设置

### ISSUE THREAD

**Issue by zhangran2616** [pure-admin/pure-admin-table#54]
分页的样式可以配置成显示表格右下角吗？紧挨着那。现在是固定下最底部。有这种属性可以设置

**Comment by xiaoxian521** [comment]
<img width="1436" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/44761321/34e24e4f-d06f-47fb-bb60-7bab6fd8072f">

**Comment by xiaoxian521** [comment]
只有图中箭头的配置项 如何特殊布局 请自行使用`css`样式覆盖
