### ISSUE TITLE
求助：异步获取表头字段，表头不渲染问题

### ISSUE THREAD

**Issue by CharleeWa** [pure-admin/pure-admin-table#55]
作者你好，我检查过相似问题，#25 和我的需求很像，但是没有解决我的问题。

我的问题是表头字段通过异步获取，重新赋值 columns 后，pure-table 没有渲染。我查询过相关文档，但是不太适用于这种抽象度极高的hook写法，后来我想到一种简单办法，即等到异步请求拿到数据并改变 columns 数组后，再渲染 pure-table组件。

```
# hook.tsx

export function useTable() {
  const done = ref(false)
  const columns: TableColumnList = [
    {
      label: '勾选列',
      type: 'selection',
      fixed: 'left',
      reserveSelection: true
    }
  ]

  onMounted(() => {
    delay(600).then(() => {
      columns.push( { label: '日期', prop: 'date' })
      columns.push( { label: '姓名', prop: 'name' })
      columns.push( { label: '地址', prop: 'address' })
      done.value = true
    })
  })

  return {
    done,
    columns
  }
}
```

```
# index.vue

<script setup lang="ts">
import { useTable } from './utils/hook'
const { done, columns } = useTable()
</script>

<template>
  <div>
    <PureTableBar v-if="done" :columns="columns">
       <template #default="{ size, dynamicColumns }">
         <pure-table  :columns="dynamicColumns" />
       </template >
    </PureTableBar>
 </div>
</template>
```
但是这种写法太粗糙。我找过pure-table-admin 的组件例子，并没有找到关于动态表头的例子，但是看到了列拖动等例子，应该是支持响应式数据变化的？所以想请教作者，我这个问题有没有更好的实现？谢谢

**Comment by xiaoxian521** [comment]
fork 仓库 https://github.com/pure-admin/pure-admin-table
在 https://github.com/pure-admin/pure-admin-table/blob/main/src/App.vue 修改你要确定的代码
运行pnpm dev 可以运行后发个仓库地址给我 有空会看看

**Comment by xiaoxian521** [comment]
暂时关闭 提供仓库地址后 在此处@ 我就行

**Comment by xiaoxian521** [comment]
我简单模拟了下，如果需要表头动态，只需将`columns`初始化为响应式即可，如下图

<img width="680" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/44761321/dd78f5ff-1268-4812-909f-946fee2c59fa">

**Comment by CharleeWa** [comment]
感谢 ！
