### ISSUE TITLE
动态列不显示了，如何排查？

### ISSUE THREAD

**Issue by zhangran2616** [pure-admin/pure-admin-table#57]
<img width="725" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/6472032/768111ec-0ca9-4d0d-b41b-c0d751a57575">
![image](https://github.com/pure-admin/pure-admin-table/assets/6472032/b3228ba2-b387-4662-a7a1-827719ad8c81)

**Comment by zhangran2616** [comment]
是因为表头这里用了渲染函数？
![image](https://github.com/pure-admin/pure-admin-table/assets/6472032/b7b8eeea-d4c8-45df-afc9-ae4b7d16e268)
 因为这里需要用国际化，所以去掉了lable，改用了渲染函数了。

**Comment by xiaoxian521** [comment]
不解决业务问题 自行解决
