### ISSUE TITLE
分页国际化问题排查以及解决办法

### ISSUE THREAD

**Issue by DBAAZzz** [pure-admin/pure-admin-table#58]
![image](https://github.com/pure-admin/pure-admin-table/assets/41032629/5c7d320b-891c-4341-b1e9-089bc098534a)

@pureadmin/table打包后的js文件引入的element-plus还是使用的是该组件node_modules下的element-plus，会导致该组件下的pagination的locale为undefined，

![image](https://github.com/pure-admin/pure-admin-table/assets/41032629/827f0b82-a9c1-4aef-8425-b3bdd399c818)

打包的时候虽然把element-plus排除了，但问题是package.json中dependencies还是有element-plus导致的，能用这个组件的项目中一定安装了element-plus依赖，可以在dependencies中把element-plus去掉吗？

![image](https://github.com/pure-admin/pure-admin-table/assets/41032629/eefb7e95-3756-40b1-885c-bb7b5a8dd1d8)

作者可以看下这个问题吗？不然每个pureadmin/table外面要包裹一层el-config-provider太麻烦了

**Comment by xiaoxian521** [comment]
。。。。肯定要安装啊 它就是基于el-table二次封装

**Comment by xiaoxian521** [comment]
不够可以把国际化相关部分打包进去

目前没有时间 抽空会看看 当然欢迎pr

**Comment by DBAAZzz** [comment]
> 不够可以把国际化相关部分打包进去
> 
> 目前没有时间 抽空会看看 当然欢迎pr

![image](https://github.com/pure-admin/pure-admin-table/assets/41032629/d093b033-85f4-4c1a-bb30-aaf65da79870)

可以通过安装插件的时候传入国际化配置，如果要提pr的话是合并到master分支吗？

**Comment by xiaoxian521** [comment]
很抱歉 现在才回复了 最新太忙了
不用每个`pureadmin/table`外面要包裹一层`el-config-provider`
一般在`App.vue`包裹一下就行，然后所有页面都可以使用国际化了，参考 https://github.com/pure-admin/vue-pure-admin/blob/main/src/App.vue#L2
如果你有什么特殊场景请列出例子哈

**Comment by DBAAZzz** [comment]
> 很抱歉 现在才回复了 最新太忙了 不用每个`pureadmin/table`外面要包裹一层`el-config-provider` 一般在`App.vue`包裹一下就行，然后所有页面都可以使用国际化了，参考 https://github.com/pure-admin/vue-pure-admin/blob/main/src/App.vue#L2 如果你有什么特殊场景请列出例子哈

没有特殊的场景，就是单纯的想使用pure-admin-table组件里的分页功能。我用的是pure-admin-thin精简版，
![image](https://github.com/pure-admin/pure-admin-table/assets/41032629/6bb77a23-5abf-49b0-b5ad-4877a7afb90a)
上面这样配置国际化对pure-admin-table里的el-pagination分页组件是不生效的。
具体原因我在最开始的issues中也提到了，项目中引入的pure-admin-table组件会优先引用dependencies下载的element-plus，而dependencies下载的element-plus和项目中下载的element-plus的国际化配置是不共通的。

**Comment by xiaoxian521** [comment]
等`3.0`版本，大概今晚发布
