### ISSUE TITLE
全局注册报错

### ISSUE THREAD

**Issue by 1031527554** [pure-admin/pure-admin-table#60]
No overload matches this call.
Overload 1 of 2,
(plugin: Plugin<[options?: PureTableInstallOptions | undefined]>, options?: PureTableInstallOptions | undefined): App<...>
, gave the following error.
Overload 2 of 2,
(plugin: Plugin<[options?: PureTableInstallOptions | undefined]>, options: [options?: PureTableInstallOptions | undefined]): App<...>
, gave the following error.

**Comment by 1031527554** [comment]
![Uploading 微信截图_20240102171235.png…]()

**Comment by xiaoxian521** [comment]
用最新版vue和vue-tsc

**Comment by xiaoxian521** [comment]
当然如果不升级的话也可以用
 ```ts
use(PureTable as any)
```

**Comment by 1031527554** [comment]
感谢问题解决了
