### ISSUE TITLE
pure-table的内容 未显示到页面

### ISSUE THREAD

**Issue by ailoved** [pure-admin/pure-admin-table#61]
在pure-admin-thin中使用的时候数据未渲染到页面
![微信图片_20240115193859](https://github.com/pure-admin/pure-admin-table/assets/19533695/c86e1ec5-8a64-430a-9bae-8bfa721f4492)
index.vue
`<script setup lang="ts">
import { ref } from "vue";
import { useMenu } from "./utils/hook";
import { PureTableBar } from "@/components/RePureTableBar";
import { useRenderIcon } from "@/components/ReIcon/src/hooks";

import Delete from "@iconify-icons/ep/delete";
import EditPen from "@iconify-icons/ep/edit-pen";
import Search from "@iconify-icons/ep/search";
import Refresh from "@iconify-icons/ep/refresh";
import AddFill from "@iconify-icons/ri/add-circle-line";

defineOptions({
  name: "SystemMenu"
});

const formRef = ref();
const tableRef = ref();
const {
  searchParam,
  loading,
  columns,
  dataList,
  menuSearch,
  resetForm,
  openDialog,
  handleDelete
} = useMenu();
</script>

<template>
  <div class="main">
    <el-form
      ref="formRef"
      :inline="true"
      :model="searchParam"
      class="search-form bg-bg_color w-[99/100] pl-8 pt-[12px]"
    >
      <el-form-item label="菜单名称：" prop="menuName">
        <el-input
          v-model="searchParam.menuName"
          placeholder="请输入名称"
          clearable
          class="!w-[200px]"
        />
      </el-form-item>
      <el-form-item label="状态：" prop="status">
        <el-select
          v-model="searchParam.status"
          placeholder="请选择状态"
          clearable
          class="!w-[180px]"
        >
          <el-option label="启用" :value="1" />
          <el-option label="停用" :value="0" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button
          type="primary"
          :icon="useRenderIcon(Search)"
          :loading="loading"
          @click="menuSearch"
        >
          搜索
        </el-button>
        <el-button :icon="useRenderIcon(Refresh)" @click="resetForm(formRef)">
          重置
        </el-button>
      </el-form-item>
    </el-form>

    <PureTableBar
      title="菜单列表"
      :columns="columns"
      :tableRef="tableRef?.getTableRef()"
      @refresh="menuSearch"
    >
      <template #buttons>
        <el-button
          type="primary"
          :icon="useRenderIcon(AddFill)"
          @click="openDialog()"
        >
          新增部门
        </el-button>
      </template>

      <template v-slot="{ size, dynamicColumns }">
        <pure-table
          ref="tableRef"
          adaptive
          :adaptiveConfig="{ offsetBottom: 32 }"
          align-whole="center"
          row-key="id"
          showOverflowTooltip
          table-layout="auto"
          default-expand-all
          :loading="loading"
          :size="size"
          :data="dataList"
          :columns="dynamicColumns"
          :header-cell-style="{
            background: 'var(--el-fill-color-light)',
            color: 'var(--el-text-color-primary)'
          }"
        >
          <template #operation="{ row }">
            <el-button
              class="reset-margin"
              link
              type="primary"
              :size="size"
              :icon="useRenderIcon(EditPen)"
              @click="openDialog()"
            >
              编辑
            </el-button>
            <el-popconfirm
              :title="`是否确认删除部门名称为${row.name}的这条数据`"
              @confirm="handleDelete()"
            >
              <template #reference>
                <el-button
                  class="reset-margin"
                  link
                  type="primary"
                  :size="size"
                  :icon="useRenderIcon(Delete)"
                >
                  删除
                </el-button>
              </template>
            </el-popconfirm>
          </template>
        </pure-table>
      </template>
    </PureTableBar>
  </div>
</template>

<style lang="scss" scoped>
.search-form {
  :deep(.el-form-item) {
    margin-bottom: 12px;
  }
}
</style>
`
hooks
`import { onMounted, reactive, ref } from "vue";
import { usePublicHooks } from "../../hooks";
import { getMenuListApi } from "@/api/system/menu";
import { handleTree, isAllEmpty } from "@pureadmin/utils";

export function useMenu() {
  const searchParam = reactive({
    menuName: "",
    status: null
  });

  const { tagStyle } = usePublicHooks();
  const loading = ref(true);
  const dataList = ref([]);
  const columns: TableColumnList = [
    {
      label: "菜单名称",
      prop: "menuName",
      width: 180,
      align: "center"
    },
    {
      label: "页面路径",
      prop: "path",
      minWidth: 100
    },
    {
      label: "路由名称",
      prop: "routerName",
      minWidth: 100
    },
    {
      label: "图标",
      prop: "meta.icon",
      minWidth: 70
    },
    {
      label: "状态",
      prop: "status",
      minWidth: 100,
      cellRenderer: ({ row, props }) => (
        <el-tag size={props.size} style={tagStyle.value(row.status)}>
          {row.status === 1 ? "启用" : "停用"}
        </el-tag>
      )
    },
    {
      label: "类型",
      prop: "button",
      minWidth: 100,
      formatter: ({ button }) => (button === 1 ? "按钮" : "菜单")
    },
    {
      label: "子类型",
      prop: "menuType",
      minWidth: 100,
      formatter: ({ menuType }) => {
        if (menuType === 1) {
          return "页面";
        } else if (menuType === 2) {
          return "目录";
        } else if (menuType === 3) {
          return "内嵌Iframe";
        } else if (menuType === 4) {
          return "外链跳转";
        }
        return "";
      }
    },
    {
      label: "创建时间",
      minWidth: 200,
      prop: "createTime"
    },
    {
      label: "操作",
      fixed: "right",
      width: 160,
      slot: "operation"
    }
  ];
  //重置查询条件
  function resetForm(formEl) {
    if (!formEl) return;
    formEl.resetFields();
    menuSearch();
  }
  //搜索菜单
  async function menuSearch() {
    loading.value = true;
    const { data } = await getMenuListApi({ button: null }); // 这里是返回一维数组结构，前端自行处理成树结构，返回格式要求：唯一id加父节点parentId，parentId取父节点id
    let newData = data;
    if (!isAllEmpty(searchParam.menuName)) {
      // 前端搜索部门名称
      newData = newData.filter(item =>
        item.menuName.includes(searchParam.menuName)
      );
    }
    if (!isAllEmpty(searchParam.status)) {
      // 前端搜索状态
      newData = newData.filter(item => item.status === searchParam.status);
    }
    dataList.value = handleTree(newData); // 处理成树结构
    setTimeout(() => {
      loading.value = false;
    }, 500);
  }
  //新增、修改弹窗
  function openDialog() {}

  function handleDelete() {}

  onMounted(() => {
    menuSearch();
  });

  return {
    loading,
    searchParam,
    columns,
    dataList,
    menuSearch,
    resetForm,
    openDialog,
    handleDelete
  };
}
`

**Comment by xiaoxian521** [comment]
解开相关注释 
https://github.com/pure-admin/pure-admin-thin/blob/main/src/main.ts#L11
