### ISSUE TITLE
cellRenderer函数在ts下突发警告

### ISSUE THREAD

**Issue by flowerwOw0316** [pure-admin/pure-admin-table#65]
更新"@pureadmin/table": "^3.0.0"， "element-plus": "2.5.1" 出现ts错误
![QQ截图20240222101343](https://github.com/pure-admin/pure-admin-table/assets/50901029/081bf2ce-7be2-4341-9303-a3fb70d0b5cd)

**Comment by xiaoxian521** [comment]
无法复习 参考pureadmin里面代码 
<img width="609" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/44761321/7657d92e-5650-456f-9c56-81a02fbf3e37">
