### ISSUE TITLE
[Vue warn]: Invalid prop name: "key" is a reserved property.

### ISSUE THREAD

**Issue by guangcaia** [pure-admin/pure-admin-table#68]
"key" 是 vue 的保留属性，在开发环境会有警告，是否考虑换一个名称？
![image](https://github.com/pure-admin/pure-admin-table/assets/72479809/4780e2ae-6423-4e0e-9bfc-7762b5adaa4b)
![image](https://github.com/pure-admin/pure-admin-table/assets/72479809/3d248053-6c85-484f-a885-d83d6b48c05f)

**Comment by xiaoxian521** [comment]
正常情况下你不需要写key

**Comment by guangcaia** [comment]
代码里面没有写 key, 是更新到 vue@3.4.19 这版本后出现的警告，应当是组件声明里面有这属性就会警告。

**Comment by xiaoxian521** [comment]
最新`vue`的更新 给很多人都带来问题，所以推荐将`vue`固定到`3.4.14`

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/pure-admin-table/commit/2cd53b4bed586ee6237ed05932d256a50a9c7cbb)
