### ISSUE TITLE
pure-table没有sort-change事件吗？

### ISSUE THREAD

**Issue by xxxx96923** [pure-admin/pure-admin-table#69]
我的分页数据要走接口的，没有sort-change事件，只能排序本页的话，那就不符合我的项目的需求了，在node_modules的@pureadmin/table中查看代码，没有找到排序相关事件，文档中也没找到

**Comment by xiaoxian521** [comment]
贴个详细代码吧 或者仓库更好 正常讲https://element-plus.org/zh-CN/component/table.html的所有属性、事件、插槽、方法都能用 而且没有破坏

**Comment by xiaoxian521** [comment]
好的
