### ISSUE TITLE
el-pagination使用了一些被废弃的方法。

### ISSUE THREAD

**Issue by InsHomePgup** [pure-admin/pure-admin-table#70]
"@pureadmin/table": "^3.1.2"
我把组件升级到了最新版本。

ElementPlusError: [ElPagination] 你使用了一些已被废弃的用法，请参考 el-pagination 的官方文档

<img width="593" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/47906083/c21e0954-3022-49f1-919a-69535c418c1b">

**Comment by xiaoxian521** [comment]
参考 https://github.com/pure-admin/vue-pure-admin 哈 目前没有这种警告

**Comment by InsHomePgup** [comment]
确实，我单独启动这个项目就是OK的，我element 和pure-table的两个版本都确认过了是一致的。。我自己清理下node_modules 和 npm的cache试试去

**Comment by InsHomePgup** [comment]
一个很难理解的事情。
```

const pagination = ref({
	pageSize: 20,
	currentPage: 1,
	total: 0,
});

我去掉currnetPage以后就没有了提示，然后我重起了一个页面，重新启动了项目，一样的代码就没有了上面那个异常。。

```
