### ISSUE TITLE
minWidth属性无效

### ISSUE THREAD

**Issue by fanhaoyang94** [pure-admin/pure-admin-table#71]
在columns配置中写了minWidth但是并不能达到elementPlus应有的效果，当我查看到源码的时候发现，作者将所有的columns设置通过拓展符传递给了ElTableColumn这将引起所有使用驼峰的属性失效，如果要使用驼峰，应该使用h()函数来进行渲染该组件
![屏幕截图 2024-03-26 154905](https://github.com/pure-admin/pure-admin-table/assets/25742238/2b43b10f-61d4-451d-8940-9efcb9293367)

**Comment by xiaoxian521** [comment]
参考https://github.com/pure-admin/vue-pure-admin 
里面大量示例

**Comment by fanhaoyang94** [comment]
当table把showOverflowTooltip属性删除后，minWidth表现异常，会因为内容的长度，影响到列宽，并不能保障minWidth设置的值
