### ISSUE TITLE
minWidth设置失效

### ISSUE THREAD

**Issue by fanhaoyang94** [pure-admin/pure-admin-table#72]
当pure-table不设置showOverflowTooltip属性时，columns内设置的minWidth无效，无法保障最小值的设置
![屏幕截图 2024-03-26 180046](https://github.com/pure-admin/pure-admin-table/assets/25742238/066d97dc-58e4-4583-a6fc-c5162955ee90)

**Comment by xiaoxian521** [comment]
el-table 会这样吗 可提供个示例

**Comment by fanhaoyang94** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiBtaW4td2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjEwMDBcIi8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIG1pbi13aWR0aD1cIjYwMFwiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgdGFibGVEYXRhID0gW1xuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdUb21Oby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319
从这个简单的实例来看el-table时不会这样的，但是我也不太确定这个场景跟pure-table的场景是否一致

**Comment by xiaoxian521** [comment]
ok
感谢 这几天我们会调查 如果确认是问题就会修复发版

**Comment by fanhaoyang94** [comment]
还有这种类型就是el-table的表现时会将el-tag超出的部分隐藏，但是pure-table的宽度会被撑开，即使我为当前列写了固定宽度width，依旧会被撑开

**Comment by antergone** [comment]
> ok 感谢 这几天我们会调查 如果确认是问题就会修复发版

我也遇到了这个问题, `pure-table` 的表头现在没办法设置宽度。

**Comment by xiaoxian521** [comment]
<img width="1504" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/44761321/e3c2b6f0-3e3f-46d0-8b76-fe76bc3a9f98">

无法复现

**Comment by fanhaoyang94** [comment]
你把旁边那一列的内容设置个超过1000px宽度的文案，再试试啊

**Comment by fanhaoyang94** [comment]
@antergone 
> 是table-layout=“auto”引起的，使用自动表格布局算法。表格及其单元格的宽度会根据内容进行调整，详情见： https://element-plus.org/zh-CN/component/table.html 或者 https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout
