### ISSUE TITLE
表格同时设置border,adaptive,show-summary后,表格边框问题

### ISSUE THREAD

**Issue by wbsllm** [pure-admin/pure-admin-table#73]
表格同时设置border,adaptive,show-summary后,表格边框问题:
底部合计行上边没有边框,  表格内容最后一行,底部没有边框

```
<pure-table
            ref="prueTableRef"
            border
            header-cell-class-name="table-row-header"
            :data="tableData"
            :columns="dynamicColumns"
            :loading="tableLoading"
            :size="size"
            row-key="id"
            :adaptive="true"
            :adaptiveConfig="adaptiveConfig"
            :max-height="maxHeight"
            show-summary
            :summary-method="getSummaries"
          >
 </pure-table>
```

![image](https://github.com/pure-admin/pure-admin-table/assets/72794088/abbc43c7-7269-4c7f-92f0-d20c2fb1328d)

**Comment by wbsllm** [comment]
不一样, 我把show-summary去掉, 边框显示就正常了

**Comment by xiaoxian521** [comment]
好的 等我抽时间看看

**Comment by xiaoxian521** [comment]
无法复现

<img width="1641" alt="image" src="https://github.com/pure-admin/pure-admin-table/assets/44761321/2f28dee5-6aae-4055-bd39-6999a3aabdd6">

**Comment by wbsllm** [comment]
![image](https://github.com/pure-admin/pure-admin-table/assets/72794088/ad8541f2-29c8-42f0-bcf0-a10860eca513)
为什么我的合计是在最下面

**Comment by wbsllm** [comment]
![image](https://github.com/pure-admin/pure-admin-table/assets/72794088/961ddcf8-1bff-4f6d-8109-86ddbc13ff12)
复现代码如图, max-height设置一下

**Comment by wbsllm** [comment]
很难受,关闭的问题消息,作者好像看不到, 新开了一个马上就被关闭,指向这里了

**Comment by xiaoxian521** [comment]
参考这个ok？
https://github.com/pure-admin/pure-admin-table/issues/73#issuecomment-2038570130

**Comment by xiaoxian521** [comment]
参考我的写法 而不是自己想咋写就咋写

**Comment by xiaoxian521** [comment]
复现不了 你非要跟我的写法不一致？

**Comment by wbsllm** [comment]
不是一样的写法吗, 我这个多了一个maxheight属性

**Comment by xiaoxian521** [comment]
参考我的写法不行吗 自己想咋写就自己fork个发个包 自己去用 真是服了

**Comment by xiaoxian521** [comment]
要啥 maxheight ？

**Comment by xiaoxian521** [comment]
这个自适应高度 你给啥maxheight
