### ISSUE TITLE
表格边框问题

### ISSUE THREAD

**Issue by wbsllm** [pure-admin/pure-admin-table#74]
![image](https://github.com/pure-admin/pure-admin-table/assets/72794088/cecfdbf1-127c-4fd7-92ce-6154afde4c44)
设置border,max-height,adaptive,show-summary这些属性后,表格最后一行数据无下边框,合计行在最下方没有上边框;
不设置max-height的话, 表格最后一行会显示下边框, 合计行在最下方依旧没有上边框;
不设置show-sunmmary则边框显示正常;
 "element-plus": "2.4.4",
"@pureadmin/table": "^3.1.2"

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/pure-admin-table/issues/73#issuecomment-2038570130
